version: '2'
services:
  db:
    image: mysql:5.7
    container_name: mds_db
    environment:
      - MYSQL_DATABASE=mds
      - MYSQL_USER=mds
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - ./transfer:/transfer
      - ./data/mysql:/var/lib/mysql
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    command:
      - '--user=mysql'
  postgres:
    image: postgres:9.6.9
    container_name: mds_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/postgresql:/var/lib/postgresql
  redis:
    image: redis:4.0.11
    container_name: mds_redis
    ports:
      - "6379:6379"
  node:
    image: node:8.12.0-jessie
    container_name: mds_node
    command: tailf /dev/null
    volumes:
      - ./src:/code
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mds_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "mds_db"
